version: '3.4'

services:
  gyminnowise.authorization.api:
    image: ${DOCKER_REGISTRY-}gyminnowiseauthorizationapi
    build:
      context: .
      dockerfile: GymInnowise.Authorization.API/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"
  gyminnowise.authorization.database:
    image: postgres:latest
    container_name: gyminnowise.authorization.database  
    environment:
      - POSTGRES_DB=GymInnowiseAuthorization
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/gym-auth-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
