
services:
  gyminnowise.userservice.api:
    image: ${DOCKER_REGISTRY-}gyminnowiseuserserviceapi
    build:
      context: ../../
      dockerfile: services/UserService/GymInnowise.UserService.API/Dockerfile
    ports:
    - "5002:5000"
    - "5003:5001"
  gyminnowise.userservice.database:
    image: postgres:latest
    container_name: gyminnowise.userservice.database
    environment:
      - POSTGRES_DB=GymInnowiseUserService
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/gym-user-db:/var/lib/postgresql/user-service
    ports:
      - 5433:5432
    