version: '3.4'

services:
  gyminnowise.gymservice.api:
    image: ${DOCKER_REGISTRY-}gyminnowisegymserviceapi
    build:
      context: ../../
      dockerfile: services/GymService/GymInnowise.GymService.API/Dockerfile
    ports:
    - "5004:5000"
    - "5005:5001"
  gyminnowise.gymservice.database:
    image: postgres:latest
    container_name: gyminnowise.gymservice.database  
    environment:
      - POSTGRES_DB=GymInnowiseGymService
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/gym-service-db:/var/lib/postgresql/gym-service
    ports:
      - 5436:5432
